/*
 * Copyright (C) 2014 Jodli
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package src.jodli.Client.Application;

import java.awt.event.ActionEvent;
import src.jodli.Client.Utilities.DatabaseModels.ModelInsuree;
import src.jodli.Client.Utilities.InsureeUtils;
import src.jodli.Client.log.Logger;

/**
 *
 * @author Jan-Olaf Becker <job87@web.de>
 */
public class InsureeFrame extends javax.swing.JFrame {

    private ModelInsuree insuree = null;

    /**
     * Creates a new InsureeFrame form to display and edit a single insuree.
     *
     * @param id ID of the insuree entry in the database.
     */
    InsureeFrame(int id) {
        // get insuree from database.
        insuree = InsureeUtils.getValue(id);
        Logger.logInfo("Opened Insuree with ID: " + id);

        initComponents();

        // add button actionlisteners.
        btn_Close.addActionListener((ActionEvent e) -> {
            Logger.logInfo("Closing Insuree with ID: " + id);
            this.dispose();
        });
        btn_Save.addActionListener((ActionEvent e) -> {
            Logger.logInfo("Saving Insuree with ID: " + id);
            // save to database.
        });

        // fill in the text fields with the text saved in database.
        txt_SurName.setText(insuree.getPrename());
        txt_PreName.setText(insuree.getSurname());
        txt_Partner_PreName.setText(insuree.getPartner_Prename());
        txt_Partner_SurName.setText(insuree.getPartner_Surname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_PreName = new javax.swing.JLabel();
        btn_Close = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        txt_SurName = new javax.swing.JTextField();
        lbl_SurName = new javax.swing.JLabel();
        txt_PreName = new javax.swing.JTextField();
        lbl_Partner_PreName = new javax.swing.JLabel();
        txt_Partner_PreName = new javax.swing.JTextField();
        lbl_Partner_SurName = new javax.swing.JLabel();
        txt_Partner_SurName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        lbl_PreName.setText("prename");

        btn_Close.setText("close");

        btn_Save.setText("save");

        lbl_SurName.setText("surname");

        lbl_Partner_PreName.setText("partner prename");

        lbl_Partner_SurName.setText("partner surname");
        lbl_Partner_SurName.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_PreName)
                    .addComponent(lbl_SurName))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Close))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_SurName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_Partner_SurName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_PreName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_Partner_PreName)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Partner_PreName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Partner_SurName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 345, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_PreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_PreName)
                    .addComponent(lbl_Partner_PreName)
                    .addComponent(txt_Partner_PreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SurName)
                    .addComponent(lbl_Partner_SurName)
                    .addComponent(txt_Partner_SurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Close)
                    .addComponent(btn_Save))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Close;
    private javax.swing.JButton btn_Save;
    private javax.swing.JLabel lbl_Partner_PreName;
    private javax.swing.JLabel lbl_Partner_SurName;
    private javax.swing.JLabel lbl_PreName;
    private javax.swing.JLabel lbl_SurName;
    private javax.swing.JTextField txt_Partner_PreName;
    private javax.swing.JTextField txt_Partner_SurName;
    private javax.swing.JTextField txt_PreName;
    private javax.swing.JTextField txt_SurName;
    // End of variables declaration//GEN-END:variables
}
